
package shopster.apis.main;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ErrorType", targetNamespace = "urn:shopster:apis:main")
public class IMainGetOrdersErrorTypeFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IMainGetOrdersErrorTypeFaultFaultMessage(String message, ErrorType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IMainGetOrdersErrorTypeFaultFaultMessage(String message, ErrorType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: shopster.apis.main.ErrorType
     */
    public ErrorType getFaultInfo() {
        return faultInfo;
    }

}
