
package shopster.apis.main;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IMain", targetNamespace = "urn:shopster:apis:main")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    shopster.apis.main.ObjectFactory.class
})
public interface IMain {


    /**
     * 
     * @param getVersionsRequest
     * @return
     *     returns shopster.apis.main.GetVersionsResponseType
     * @throws IMainGetVersionsErrorTypeFaultFaultMessage
     */
    @WebMethod(operationName = "GetVersions", action = "GetVersionsRequest")
    @WebResult(name = "GetVersionsResponse", targetNamespace = "urn:shopster:apis:main", partName = "GetVersionsResponse")
    public GetVersionsResponseType getVersions(
        @WebParam(name = "GetVersionsRequest", targetNamespace = "urn:shopster:apis:main", partName = "GetVersionsRequest")
        GetVersionsRequestType getVersionsRequest)
        throws IMainGetVersionsErrorTypeFaultFaultMessage
    ;

    /**
     * 
     * @param getInventoryItemsRequest
     * @return
     *     returns shopster.apis.main.GetInventoryItemsResponseType
     * @throws IMainGetInventoryItemsErrorTypeFaultFaultMessage
     */
    @WebMethod(operationName = "GetInventoryItems", action = "GetInventoryItemsRequest")
    @WebResult(name = "GetInventoryItemsResponse", targetNamespace = "urn:shopster:apis:main", partName = "GetInventoryItemsResponse")
    public GetInventoryItemsResponseType getInventoryItems(
        @WebParam(name = "GetInventoryItemsRequest", targetNamespace = "urn:shopster:apis:main", partName = "GetInventoryItemsRequest")
        GetInventoryItemsRequestType getInventoryItemsRequest)
        throws IMainGetInventoryItemsErrorTypeFaultFaultMessage
    ;

    /**
     * 
     * @param getInventoryCategoriesRequest
     * @return
     *     returns shopster.apis.main.GetInventoryCategoriesResponseType
     * @throws IMainGetInventoryCategoriesErrorTypeFaultFaultMessage
     */
    @WebMethod(operationName = "GetInventoryCategories", action = "GetInventoryCategoriesRequest")
    @WebResult(name = "GetInventoryCategoriesResponse", targetNamespace = "urn:shopster:apis:main", partName = "GetInventoryCategoriesResponse")
    public GetInventoryCategoriesResponseType getInventoryCategories(
        @WebParam(name = "GetInventoryCategoriesRequest", targetNamespace = "urn:shopster:apis:main", partName = "GetInventoryCategoriesRequest")
        GetInventoryCategoriesRequestType getInventoryCategoriesRequest)
        throws IMainGetInventoryCategoriesErrorTypeFaultFaultMessage
    ;

    /**
     * 
     * @param getOrdersRequest
     * @return
     *     returns shopster.apis.main.GetOrdersResponseType
     * @throws IMainGetOrdersErrorTypeFaultFaultMessage
     */
    @WebMethod(operationName = "GetOrders", action = "GetOrdersRequest")
    @WebResult(name = "GetOrdersResponse", targetNamespace = "urn:shopster:apis:main", partName = "GetOrdersResponse")
    public GetOrdersResponseType getOrders(
        @WebParam(name = "GetOrdersRequest", targetNamespace = "urn:shopster:apis:main", partName = "GetOrdersRequest")
        GetOrdersRequestType getOrdersRequest)
        throws IMainGetOrdersErrorTypeFaultFaultMessage
    ;

    /**
     * 
     * @param verifyPlaceOrderRequest
     * @return
     *     returns shopster.apis.main.VerifyPlaceOrderResponseType
     * @throws IMainVerifyPlaceOrderErrorTypeFaultFaultMessage
     */
    @WebMethod(operationName = "VerifyPlaceOrder", action = "VerifyPlaceOrderRequest")
    @WebResult(name = "VerifyPlaceOrderResponse", targetNamespace = "urn:shopster:apis:main", partName = "VerifyPlaceOrderResponse")
    public VerifyPlaceOrderResponseType verifyPlaceOrder(
        @WebParam(name = "VerifyPlaceOrderRequest", targetNamespace = "urn:shopster:apis:main", partName = "VerifyPlaceOrderRequest")
        VerifyPlaceOrderRequestType verifyPlaceOrderRequest)
        throws IMainVerifyPlaceOrderErrorTypeFaultFaultMessage
    ;

    /**
     * 
     * @param placeOrderRequest
     * @return
     *     returns shopster.apis.main.PlaceOrderResponseType
     * @throws IMainPlaceOrderErrorTypeFaultFaultMessage
     */
    @WebMethod(operationName = "PlaceOrder", action = "PlaceOrderRequest")
    @WebResult(name = "PlaceOrderResponse", targetNamespace = "urn:shopster:apis:main", partName = "PlaceOrderResponse")
    public PlaceOrderResponseType placeOrder(
        @WebParam(name = "PlaceOrderRequest", targetNamespace = "urn:shopster:apis:main", partName = "PlaceOrderRequest")
        PlaceOrderRequestType placeOrderRequest)
        throws IMainPlaceOrderErrorTypeFaultFaultMessage
    ;

    /**
     * 
     * @param getUserInfoRequest
     * @return
     *     returns shopster.apis.main.GetUserInfoResponseType
     * @throws IMainGetUserInfoErrorTypeFaultFaultMessage
     */
    @WebMethod(operationName = "GetUserInfo", action = "GetUserInfoRequest")
    @WebResult(name = "GetUserInfoResponse", targetNamespace = "urn:shopster:apis:main", partName = "GetUserInfoResponse")
    public GetUserInfoResponseType getUserInfo(
        @WebParam(name = "GetUserInfoRequest", targetNamespace = "urn:shopster:apis:main", partName = "GetUserInfoRequest")
        GetUserInfoRequestType getUserInfoRequest)
        throws IMainGetUserInfoErrorTypeFaultFaultMessage
    ;

}
